# Generated by Django 4.2.1 on 2023-07-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='AccessLevel',
            field=models.CharField(blank=True, choices=[('admin', 'مدیر'), ('user', 'کاربر'), ('ins', 'بازرس')], max_length=5, null=True, verbose_name='سطح دسترسی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fname',
            field=models.CharField(blank=True, max_length=20, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lname',
            field=models.CharField(blank=True, max_length=20, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='تلفن'),
        ),
    ]
