# Generated by Django 5.0.6 on 2024-12-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_warehouseorder_delete_myuser_delete_warehouseorders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('company_nid', models.CharField(blank=True, max_length=12, null=True)),
                ('accepter_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WhUsers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='WhUsers',
        ),
    ]
