# Generated by Django 4.2.1 on 2023-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameLast', models.CharField(max_length=20, null=True)),
                ('cellphone', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=20, null=True)),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('datatime_created', models.DateTimeField(auto_now_add=True)),
                ('datatime_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
