# Generated by Django 4.2.1 on 2023-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiryHistory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiryhistory',
            name='Code_type',
        ),
        migrations.RemoveField(
            model_name='inquiryhistory',
            name='Customer_Id',
        ),
        migrations.AddField(
            model_name='inquiryhistory',
            name='requestText',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiryhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
