# Generated by Django 4.2.1 on 2023-07-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InspectionDetails', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiondetail',
            name='scanDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
