# Generated by Django 4.2.1 on 2023-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('nid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=5)),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
