# Generated by Django 4.2.1 on 2023-07-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nid',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='کدملی شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='prefix',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='پیش کد'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='تلفن'),
        ),
    ]
