# Generated by Django 5.0.6 on 2024-12-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_address_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
    ]
