# Generated by Django 5.0.6 on 2024-12-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False},
        ),
    ]
