# Generated by Django 5.0.6 on 2024-12-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False, 'ordering': ['company_fa_name']},
        ),
    ]
