# Generated by Django 5.0.6 on 2024-12-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_inspection_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='task',
            field=models.CharField(max_length=50, verbose_name='عنوان '),
        ),
    ]
