# Generated by Django 5.0.6 on 2024-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_inspection_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='task',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
