# Generated by Django 5.0.6 on 2024-12-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_auto_20241203_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={},
        ),
    ]
