# Generated by Django 5.0.6 on 2024-12-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_alter_inspection_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inspection',
            table='inspections_inspection',
        ),
    ]
