# Generated by Django 5.0.6 on 2024-12-09 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options'),
        ('inspections', '0014_alter_inspection_company_alter_inspection_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='company',
            field=models.ForeignKey(db_column='National_Id', on_delete=django.db.models.deletion.CASCADE, to='companies.company', to_field='national_id', verbose_name='مکان مراجعه'),
        ),
    ]
