# Generated by Django 5.0.6 on 2024-12-09 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options'),
        ('inspections', '0017_alter_inspection_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='company',
            field=models.ForeignKey(db_column='Nationalid_id', on_delete=django.db.models.deletion.CASCADE, to='companies.company', to_field='national_id', verbose_name='مکان مراجعه'),
        ),
    ]
