# Generated by Django 5.0.6 on 2024-12-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0019_alter_inspection_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'managed': False},
        ),
    ]
