# Generated by Django 5.0.6 on 2024-12-17 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_options'),
        ('inspections', '0021_alter_inspection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='done',
            field=models.BooleanField(default=False, verbose_name='انجام شده'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='companies.company', to_field='national_id', verbose_name='مکان مراجعه'),
        ),
    ]
