# Generated by Django 5.0.6 on 2024-12-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('whOrderId', models.IntegerField(blank=True, null=True)),
                ('whUserId', models.IntegerField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ScanLogs',
                'managed': False,
            },
        ),
    ]
