# Generated by Django 5.0.6 on 2024-12-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('OrderCode', models.CharField(max_length=20, unique=True)),
                ('ProductCode', models.CharField(blank=True, max_length=14, null=True)),
                ('SupplierCode', models.CharField(blank=True, max_length=11, null=True)),
                ('PublisherCode', models.CharField(blank=True, max_length=11, null=True)),
                ('Numberinpack', models.IntegerField(blank=True, default=0, null=True)),
                ('NumberOfOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('PakingLevel', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('BatchNumber', models.CharField(blank=True, max_length=80, null=True)),
                ('ProduceDate', models.CharField(blank=True, max_length=10, null=True)),
                ('ExpDate', models.CharField(blank=True, max_length=10, null=True)),
                ('ReleaseNumber', models.CharField(blank=True, max_length=64, null=True)),
                ('ReleaseDate', models.CharField(blank=True, max_length=10, null=True)),
                ('OrderDate', models.CharField(blank=True, max_length=10, null=True)),
                ('NumberOfCoded', models.IntegerField(blank=True, default=0, null=True)),
                ('LastCodingDate', models.CharField(blank=True, max_length=20, null=True)),
                ('factoryPrice', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('UserCode', models.CharField(blank=True, max_length=50, null=True)),
                ('InsertDate', models.CharField(blank=True, default=models.F('InsertDate'), max_length=10, null=True)),
                ('Done', models.SmallIntegerField(blank=True, null=True)),
                ('FullPackcount', models.IntegerField(blank=True, null=True)),
                ('TotalCount', models.IntegerField(blank=True, null=True)),
                ('MiniOrigin', models.SmallIntegerField(blank=True, null=True)),
                ('invoiceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('TempIRC', models.CharField(blank=True, max_length=50, null=True)),
                ('Selected', models.BooleanField(blank=True, null=True)),
                ('Accepted', models.BooleanField(blank=True, null=True)),
                ('NumberOfPrinted', models.IntegerField(blank=True, default=0, null=True)),
                ('Userid', models.IntegerField(blank=True, null=True)),
                ('XmlStatus', models.BooleanField(blank=True, default=False, null=True)),
                ('archiveprefix', models.CharField(blank=True, max_length=3, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
