# Generated by Django 4.2.1 on 2023-07-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='نام محصصول')),
                ('gtin', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='کد جهانی تجاری')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='قیمت')),
                ('description', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('image', models.ImageField(null=True, upload_to='products/', verbose_name='عکس')),
                ('irc', models.CharField(max_length=16, null=True, verbose_name='پروانه بهداشتی')),
                ('datatime_created', models.DateTimeField(auto_now_add=True)),
                ('datatime_modified', models.DateTimeField(auto_now=True)),
                ('OC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='شرکت تولید کننده')),
            ],
        ),
    ]
