# Generated by Django 5.0.6 on 2024-11-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
